# Generated by Django 5.2.16 on 2026-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portconnectionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_modal', models.TextField()),
                ('source_ip', models.TextField()),
                ('source_port', models.TextField()),
                ('source_name', models.TextField()),
                ('destination_modal', models.TextField()),
                ('destination_ip', models.TextField()),
                ('destination_port', models.TextField()),
                ('destination_name', models.TextField()),
            ],
            options={
                'db_table': 'port_connection',
            },
        ),
    ]
