-- Escalation mail (BOD / device policy) — upgrade existing `policy` table.
-- Run once against linkedeye MySQL if Django migrations are not used.

ALTER TABLE policy ADD COLUMN IF NOT EXISTS subject_category VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE policy ADD COLUMN IF NOT EXISTS device_type VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE policy ADD COLUMN IF NOT EXISTS device_ip VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE policy ADD COLUMN IF NOT EXISTS device_friendly_name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE policy ADD COLUMN IF NOT EXISTS is_enabled TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE policy ADD COLUMN IF NOT EXISTS created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE policy ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
