apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: fs-dev1-le

      serviceAccountName: sa-ui

      imagePullSecrets:
        - name: finspot-registry

      containers:
        - name: ui
          image: harbor-dev.finspot.in/ui/ui:2.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          tty: true
          securityContext:
            privileged: true
            runAsUser: 0

          env:
            - name: PORTAL_URL
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: PORTAL_URL
            - name: WEBSOCKET_PREFIX_URL
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: WEBSOCKET_PREFIX_URL
            - name: ANALYTICS_DASHBOARD_PREFIX_URL
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: ANALYTICS_DASHBOARD_PREFIX_URL
            - name: LE_CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: LE_CSRF_TRUSTED_ORIGINS
            - name: DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: K8S_CS
            - name: LINKEDEYE_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: LINKEDEYE_EMAIL
            - name: LINKEDEYE_EMAIL_APPKEY
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: LINKEDEYE_EMAIL_APPKEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: GOOGLE_SECRET
            - name: GOOGLE_SITE_ID
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: GOOGLE_SITE_ID
            - name: GOOGLE_ALLOW_DOMAINS
              valueFrom:
                configMapKeyRef:
                  name: env-details
                  key: GOOGLE_ALLOW_DOMAINS

            - name: DATABASE_NAME
              value: linkedeye
            - name: DJANGO_DB_CONN_MAX_AGE
              value: "60"
            - name: GUNICORN_WORKERS
              value: "4"

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ui
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DB_HOST
              value: mysql
            - name: MYSQL_DB_PORT
              value: "3306"

            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: REDIS_PASSWORD
            - name: REDIS_PORT
              value: "6379"

            - name: NEO4J_HOST
              value: entity
            - name: NEO4J_PORT
              value: "7474"
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-ui
                  key: NEO4J_PASS

            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: linkedeye
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-ui
                  key: POSTGRES_PASS
            - name: POSTGRES_SUPERSET_DB
              value: superset

            - name: RMQ_USER
              value: linkedeye
            - name: RMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-ui
                  key: RMQ_PASS

            - name: ELASTIC_HOST
              value: es
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-ui
                  key: ELASTIC_PASS

            - name: VAULT_HOST
              value: vault
            - name: VAULT_PORT
              value: "8200"

            - name: ANALYTICS_DASHBOARD_USER
              value: linkedeyedashboard
            - name: ANALYTICS_DASHBOARD_PASS
              value: linkedeyedashboard
            - name: DASHBOARD_USERNAME
              value: admin
            - name: DASHBOARD_PASSWORD
              value: admin

          volumeMounts:
            - name: secrets-store-ui
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - mountPath: /vault/keys.json
              name: le
              subPath: vault/keys.json
            - mountPath: /usr/src/monitor
              name: le
              subPath: monitor/etc
            - mountPath: /var/run/docker.sock
              name: host-docker-sock
            - mountPath: /stackstorm/configs
              name: le
              subPath: automation/st2-packs-configs
            - mountPath: /usr/src/logs/
              name: le-noren-core
              subPath: finspot/logs/le
            - mountPath: /usr/src/prom-conf
              name: le
              subPath: prom-conf
            - mountPath: /usr/src/static/app/usericons
              name: le
              subPath: usericons

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"

      volumes:
        - name: secrets-store-ui
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "spc-ui"
        - name: le
          persistentVolumeClaim:
            claimName: data-le
        - name: le-noren-core
          persistentVolumeClaim:
            claimName: le-noren-core
        - name: host-docker-sock
          hostPath:
            path: /var/run/docker.sock

      restartPolicy: Always
