# Generated by Django 5.2.16 on 2026-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditlogsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField()),
                ('action', models.TextField()),
                ('status', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'auditlogs',
            },
        ),
    ]
