# Generated by Django 5.2.16 on 2026-07-31 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesites', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='policynotifiModel',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_category', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('device_friendly_name', models.CharField(max_length=255)),
                ('device_ip', models.CharField(max_length=100)),
                ('categories', models.TextField()),
                ('escalation_mails', models.TextField()),
                ('definite_mails', models.TextField()),
                ('approval_timer', models.IntegerField(default=0)),
                ('resolution_timer', models.IntegerField(default=0)),
                ('escalation_required', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='subsiteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_site', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesites.sitemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subsite',
            },
        ),
    ]
